---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/nourrissons
  label: Maternité & Nourrissons
  create: all
  match: "**/*"
- type: document
  path: content/legal.md
  label: Mentions légales
- type: directory
  path: content/articles
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: content/presse
  label: Presse
  create: all
  match: "**/*"
- type: directory
  path: content/therapies
  label: Therapies
  create: all
  match: "**/*"
- type: directory
  path: content/pourquoi
  label: Pourquoi
  create: all
  match: "**/*"
- type: directory
  path: content/cabinet
  label: Le Cabinet
  create: all
  match: "**/*"
- type: directory
  path: content/honoraires
  label: Honoraires
  create: all
  match: "**/*"
- type: directory
  path: content/accueil
  label: Accueil
  create: all
  match: "**/*"
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.54.0
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: 0.54.0
